"""Initial migration with all CES models

Revision ID: 528d883a84f1
Revises: 
Create Date: 2026-10-01 11:17:16.601358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528d883a84f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_company_name', 'customer', ['company_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_index('ix_user_is_active', 'user', ['is_active'], unique=False)
    op.create_table('work_center',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_work_center_code', 'work_center', ['code'], unique=False)
    op.create_index('ix_work_center_is_active', 'work_center', ['is_active'], unique=False)
    op.create_table('machine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_center_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('machine_code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year_of_installation', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('mhr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recommended_mhr', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mhr_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mhr_updated_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mhr_updated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_center.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_machine_is_active', 'machine', ['is_active'], unique=False)
    op.create_index('ix_machine_machine_code', 'machine', ['machine_code'], unique=False)
    op.create_index('ix_machine_work_center_id', 'machine', ['work_center_id'], unique=False)
    op.create_table('mhr_particular',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_input', sa.Boolean(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('default_sequence', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_mhr_particular_code', 'mhr_particular', ['code'], unique=False)
    op.create_index('ix_mhr_particular_is_active', 'mhr_particular', ['is_active'], unique=False)
    op.create_table('part_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_part_type_name', 'part_type', ['name'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_number', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_product_name', 'product', ['product_name'], unique=False)
    op.create_index('ix_product_product_number', 'product', ['product_number'], unique=False)
    op.create_table('assembly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('parent_assembly_id', sa.Integer(), nullable=True),
    sa.Column('assembly_number', sa.String(length=50), nullable=False),
    sa.Column('assembly_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_assembly_id'], ['assembly.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assembly_assembly_number', 'assembly', ['assembly_number'], unique=False)
    op.create_index('ix_assembly_parent_assembly_id', 'assembly', ['parent_assembly_id'], unique=False)
    op.create_index('ix_assembly_product_id', 'assembly', ['product_id'], unique=False)
    op.create_table('cost_estimation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estimation_number', sa.String(length=50), nullable=False),
    sa.Column('estimation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estimation_number')
    )
    op.create_index('ix_cost_estimation_customer_id', 'cost_estimation', ['customer_id'], unique=False)
    op.create_index('ix_cost_estimation_estimation_date', 'cost_estimation', ['estimation_date'], unique=False)
    op.create_index('ix_cost_estimation_estimation_number', 'cost_estimation', ['estimation_number'], unique=False)
    op.create_index('ix_cost_estimation_product_id', 'cost_estimation', ['product_id'], unique=False)
    op.create_table('machine_mhr_value',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('particular_id', sa.Integer(), nullable=False),
    sa.Column('is_applicable', sa.Boolean(), nullable=False),
    sa.Column('input_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('computed_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.ForeignKeyConstraint(['particular_id'], ['mhr_particular.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'particular_id', name='uq_machine_particular')
    )
    op.create_index('ix_machine_mhr_value_machine_id', 'machine_mhr_value', ['machine_id'], unique=False)
    op.create_index('ix_machine_mhr_value_particular_id', 'machine_mhr_value', ['particular_id'], unique=False)
    op.create_table('estimation_additional_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estimation_id', sa.Integer(), nullable=False),
    sa.Column('cost_name', sa.String(length=255), nullable=False),
    sa.Column('cost_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estimation_id'], ['cost_estimation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_estimation_additional_cost_estimation_id', 'estimation_additional_cost', ['estimation_id'], unique=False)
    op.create_table('part',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.Column('part_type_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('part_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assembly.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['part_type_id'], ['part_type.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_part_assembly_id', 'part', ['assembly_id'], unique=False)
    op.create_index('ix_part_part_number', 'part', ['part_number'], unique=False)
    op.create_index('ix_part_part_type_id', 'part', ['part_type_id'], unique=False)
    op.create_index('ix_part_product_id', 'part', ['product_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('assembly_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assembly.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_assembly_id', 'document', ['assembly_id'], unique=False)
    op.create_index('ix_document_file_name', 'document', ['file_name'], unique=False)
    op.create_index('ix_document_part_id', 'document', ['part_id'], unique=False)
    op.create_table('operation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('operation_number', sa.String(length=50), nullable=False),
    sa.Column('operation_name', sa.String(length=255), nullable=False),
    sa.Column('work_center_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('setup_time', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cycle_time', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('work_instructions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_center.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operation_machine_id', 'operation', ['machine_id'], unique=False)
    op.create_index('ix_operation_operation_number', 'operation', ['operation_number'], unique=False)
    op.create_index('ix_operation_part_id', 'operation', ['part_id'], unique=False)
    op.create_index('ix_operation_work_center_id', 'operation', ['work_center_id'], unique=False)
    op.create_table('estimation_operation_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('estimation_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('setup_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cycle_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('part_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mhr_rate_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('machining_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estimation_id'], ['cost_estimation.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_estimation_operation_cost_estimation_id', 'estimation_operation_cost', ['estimation_id'], unique=False)
    op.create_index('ix_estimation_operation_cost_machine_id', 'estimation_operation_cost', ['machine_id'], unique=False)
    op.create_index('ix_estimation_operation_cost_operation_id', 'estimation_operation_cost', ['operation_id'], unique=False)
    op.create_index('ix_estimation_operation_cost_part_id', 'estimation_operation_cost', ['part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_estimation_operation_cost_part_id', table_name='estimation_operation_cost')
    op.drop_index('ix_estimation_operation_cost_operation_id', table_name='estimation_operation_cost')
    op.drop_index('ix_estimation_operation_cost_machine_id', table_name='estimation_operation_cost')
    op.drop_index('ix_estimation_operation_cost_estimation_id', table_name='estimation_operation_cost')
    op.drop_table('estimation_operation_cost')
    op.drop_index('ix_operation_work_center_id', table_name='operation')
    op.drop_index('ix_operation_part_id', table_name='operation')
    op.drop_index('ix_operation_operation_number', table_name='operation')
    op.drop_index('ix_operation_machine_id', table_name='operation')
    op.drop_table('operation')
    op.drop_index('ix_document_part_id', table_name='document')
    op.drop_index('ix_document_file_name', table_name='document')
    op.drop_index('ix_document_assembly_id', table_name='document')
    op.drop_table('document')
    op.drop_index('ix_part_product_id', table_name='part')
    op.drop_index('ix_part_part_type_id', table_name='part')
    op.drop_index('ix_part_part_number', table_name='part')
    op.drop_index('ix_part_assembly_id', table_name='part')
    op.drop_table('part')
    op.drop_index('ix_estimation_additional_cost_estimation_id', table_name='estimation_additional_cost')
    op.drop_table('estimation_additional_cost')
    op.drop_index('ix_machine_mhr_value_particular_id', table_name='machine_mhr_value')
    op.drop_index('ix_machine_mhr_value_machine_id', table_name='machine_mhr_value')
    op.drop_table('machine_mhr_value')
    op.drop_index('ix_cost_estimation_product_id', table_name='cost_estimation')
    op.drop_index('ix_cost_estimation_estimation_number', table_name='cost_estimation')
    op.drop_index('ix_cost_estimation_estimation_date', table_name='cost_estimation')
    op.drop_index('ix_cost_estimation_customer_id', table_name='cost_estimation')
    op.drop_table('cost_estimation')
    op.drop_index('ix_assembly_product_id', table_name='assembly')
    op.drop_index('ix_assembly_parent_assembly_id', table_name='assembly')
    op.drop_index('ix_assembly_assembly_number', table_name='assembly')
    op.drop_table('assembly')
    op.drop_index('ix_product_product_number', table_name='product')
    op.drop_index('ix_product_product_name', table_name='product')
    op.drop_table('product')
    op.drop_index('ix_part_type_name', table_name='part_type')
    op.drop_table('part_type')
    op.drop_index('ix_mhr_particular_is_active', table_name='mhr_particular')
    op.drop_index('ix_mhr_particular_code', table_name='mhr_particular')
    op.drop_table('mhr_particular')
    op.drop_index('ix_machine_work_center_id', table_name='machine')
    op.drop_index('ix_machine_machine_code', table_name='machine')
    op.drop_index('ix_machine_is_active', table_name='machine')
    op.drop_table('machine')
    op.drop_index('ix_work_center_is_active', table_name='work_center')
    op.drop_index('ix_work_center_code', table_name='work_center')
    op.drop_table('work_center')
    op.drop_index('ix_user_is_active', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_customer_company_name', table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
